name: Upload release tar.gz

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
      checks: write
      actions: read
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read

    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Download tarball archive
      uses: suisei-cn/actions-download-file@v1.6.0
      id: download-tarball
      with:
        url: 'https://github.com/SHTOOLS/SHTOOLS/archive/${{ env.RELEASE_VERSION }}/ldraw-${{ env.RELEASE_VERSION }}.tar.gz'

    - name: Upload tarball as release asset
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["${{ steps.download-tarball.outputs.filename }}"]'
